### ISSUE TITLE
Chemical Notation Support

### ISSUE THREAD

**Issue by jetrosut** [jbyuki/nabla.nvim#1]
Hey, thank you for the plugin, I have yet to find anything like nabla.nvim. I am trying to use Vim to take scientific notes, which often contain chemical and mathematical formulas.

Though, the plugin is quite primitive (naturally), so it doesn't really help me to take notes in Vim. See the image below where I am getting an error.

![nablaerror](https://user-images.githubusercontent.com/71877689/104689248-0d797680-56b7-11eb-9d1c-d338afce27e3.png)

This is how it is supposed to be rendered:
![notion](https://user-images.githubusercontent.com/71877689/104689709-da83b280-56b7-11eb-8dcb-3be3dd00fc18.png)

I have to add that the italic letters are of no significance, what's important is formulas like H_{12} to work.

**Comment by jbyuki** [comment]
The parser will need to be changed in order to support chemical formulas. This will take some time but it's probably feasible. I will see what I can do when I have some spare time.

How would you like to formula to be rendered in ASCII? so that I have a reference.

**Comment by jbyuki** [comment]
Something like this?
```
C₅H₁₂(l) + 8O₂(g) → 5CO₂ + 6H₂O(l)
```

**Comment by jetrosut** [comment]
> Something like this?
> 
> ```
> C₅H₁₂(l) + 8O₂(g) → 5CO₂(g) + 6H₂O(l)
> ```

Exactly like that!

**Comment by jbyuki** [comment]
Could you test if it's working for you?

I added basic support for chemical formulas in the last commit. It was much easier than a thought (well the code is also not that pretty).

You do not need to use the Latex { } for subscript because it's already supported as the parser parses the number as a whole.

Try like this:

```
C_5H_12(l)+8O_2(g)->5CO_2(g)+H_2O(l)
```

Try some other formulas to see if it works overall.

**Comment by jetrosut** [comment]
The formula I provided above looks like this:
![formula1](https://user-images.githubusercontent.com/71877689/104754931-a4bde880-570e-11eb-9cbd-659e5cb9d0fe.png)
The arrow is not rendered properly but it could be an issue on my end.

------

Here's another 'formula', this is how it should look like:
![configproper](https://user-images.githubusercontent.com/71877689/104755087-dcc52b80-570e-11eb-95b1-50e2d6b68afb.png)

And this is how it looks:
![configbroken](https://user-images.githubusercontent.com/71877689/104755122-e8185700-570e-11eb-8d62-830e6060339e.png)

I also tried to put spaces between the characters but I got the following error: `E5105: Error while calling lua chunk: ...pData\Local\nvim\plugged\nabla.nvim\lua\nabla\parser.lua:591: attempt to call field 'priority' (a nil value)`.

------

 There are also formulas like this, for which I use \cdot:

![dotted](https://user-images.githubusercontent.com/71877689/104755873-e0a57d80-570f-11eb-9d36-c1b3cb2abf53.png)

Though, obviously it won't recognize `\cdot` and the arrow renders like a square, (unidentified character) anyway, even when copy-pasted. I tried to delete the arrow but still I get `nabla error!`:

![errorDotted](https://user-images.githubusercontent.com/71877689/104755911-ec913f80-570f-11eb-8b10-e03fb1d68e6e.png)

------

For Chemistry, I think curly brackets, { }, are necessary because you will get an error if you want to add a plus or a minus sign in the superscript after a number, as shown in the image below.

![s2](https://user-images.githubusercontent.com/71877689/104756859-2e6eb580-5711-11eb-98b8-28f393e54c81.png)

------

When you need to have both a superscript and a subscript on a character, it places the superscript on the subscript. If you try to type the subscript first, you get an error.

Compare this: 

![supersub](https://user-images.githubusercontent.com/71877689/104757434-edc36c00-5711-11eb-9f96-b12a413e778d.png)

To this:

![subsuper](https://user-images.githubusercontent.com/71877689/104757463-f2882000-5711-11eb-92a6-263e536fd4ef.png)

------

I also look into replicating this in Vim:

![LetterSubscript](https://user-images.githubusercontent.com/71877689/104758167-e18bde80-5712-11eb-877a-4186ffc20038.png)

But I get an error: `E5105: Error while calling lua chunk: ...ppData\Local\nvim\plugged\nabla.nvim\lua\nabla\ascii.lua:212: attempt to concatenate a nil value`.

I also get that blank square character whenever I try to make a letter subscript. Probably a problem on my end.

------

Fractions in sub/superscripts would be quite useful as well.

------

Symbols like approximately equal, ≈, would be a neat addition.

------

To produce the following, I am converted `theta` to `θ` in a separate line, then moved it next to `sin`. I copy-pasted `≈` and moved `λ / D` manually from a different set of lines.
![firstminimum](https://user-images.githubusercontent.com/71877689/104760974-084c1400-5717-11eb-93c6-c9178ba39adf.png)

------

I can't test `integer` yet as it doesn't render properly on this system for some reason. Anyway, I do realize many of the things I included in this comment might be irrelevant or simply not suitable for Neovim but I just wanted to let it all out, just in case it benefits someone out there.

**Comment by jbyuki** [comment]
> The arrow is not rendered properly but it could be an issue on my end.

The font seems to be issue. Changing it will fix the problem. I use [Fantasque Sans](https://github.com/belluzj/fantasque-sans) which supports special Unicode. There are plenty of others.

> Though, obviously it won't recognize \cdot and the arrow renders like a square, (unidentified character) anyway, even when copy-pasted. I tried to delete the arrow but still I get nabla error!:

Yes, if you pass Latex commands, the parser will error because it won't be able to recognize the syntax.

> For Chemistry, I think curly brackets, { }, are necessary because you will get an error if you want to add a plus or a minus sign in the superscript after a number, as shown in the image below.

After thinking for a bit, I think it might be interesting to switch to a standard LaTeX parser instead of this math notations I'm using currently. I came up with a simple [design document](https://github.com/jbyuki/nabla.nvim/wiki/design-document) for nabla.nvim which you could check out .

Could write what you need and approve? (it should be publicly editable)

> Fractions in sub/superscripts would be quite useful as well.

Already possible, see https://github.com/jbyuki/nabla.nvim/blob/03e3a55375fac32f2c060d10095d8a44bf491326/test/input.txt#L37

> To produce the following, I converted theta to θ in a separate line, then moved it next to sin. I copy-pasted ≈ and moved λ / D manually from a different set of lines.

Also possible, though the approximatively equal is different (but I could change it):

```
sin(theta) ~= lambda/D
```

> I can't test integer yet as it doesn't render properly on this system for some reason. Anyway, I do realize many of the things I included in this comment might be irrelevant or simply not suitable for Neovim but I just wanted to let it all out, just in case it benefits someone out there.

The rendering of integral is not so pretty but should be functional with the correct font. Something like:
https://github.com/jbyuki/nabla.nvim/blob/03e3a55375fac32f2c060d10095d8a44bf491326/test/input.txt#L27

The design document is to have something so that we could use as a reference. Who knows, maybe I will maybe never implement it. But at least, we would have something written. It will be essentially the specifications of such a plugin.

**Comment by jetrosut** [comment]
> Yes, if you pass Latex commands, the parser will error because it won't be able to recognize the syntax.
I see but how do I go about inserting a middle dot, then? Unicode has a middle dot character.

> sin(theta) ~= lambda/D
This works but what I meant was sintheta without parantheses. Though, it makes no difference, so I'm guessing there is no point in wasting time on this one. The approximately equal sign is fine as well but when there is a tilde, ~, in the line, I get a nil instead of the rendered equation. See the image below.

![nil](https://user-images.githubusercontent.com/71877689/104834456-32efb700-5854-11eb-983d-1be174827ef2.png)

> https://github.com/jbyuki/nabla.nvim/blob/03e3a55375fac32f2c060d10095d8a44bf491326/test/input.txt#L27
`Integral` seems to be working pretty well, also, thank you for bearing with me when I'm sleepy, only now I notice I called integral an integer.

-------

As for fractions, I was thinking about something like this ⅕ but I don't think it is possible.

**Comment by jbyuki** [comment]
> I see but how do I go about inserting a middle dot, then? Unicode has a middle dot character.

> This works but what I meant was sintheta without parantheses. Though, it makes no difference, so I'm guessing there is no point in wasting time on this one. The approximately equal sign is fine as well but when there is a tilde, ~, in the line, I get a nil instead of the rendered equation. See the image below.

I see then the LaTeX syntax which is more flexible would be the solution here. I will try to implement one when I have some spare time.

Also please look at the [design document](https://github.com/jbyuki/nabla.nvim/wiki/design-document) if you wish to have something as a feature. It will provide me with written reference.

> As for fractions, I was thinking about something like this ⅕ but I don't think it is possible.

I wasn't aware of Unicode for fractions, there are probably implementable.

**Comment by jbyuki** [comment]
Do you have programming capabilities? You might help me with the process.

**Comment by jetrosut** [comment]
> Do you have programming capabilities? You might help me with the process.
>
I don't have any experience in programming, I don't think I can help although I wish to.

**Comment by jetrosut** [comment]
The recently added LaTeX syntax made it much better, thank you. I am now able to do \cdot and write sub/superscripts using curly brackets.

I would also like to point out the spaces between characters. As seen in the image below, I didn't put any spaces between characters.
![equ1](https://user-images.githubusercontent.com/71877689/104847306-2428f480-5894-11eb-9b3c-1889699ad92f.png)

However, when it renders, there is a space between each element of the equation:
![equ2](https://user-images.githubusercontent.com/71877689/104847334-3efb6900-5894-11eb-95ed-5ee3975d0aa1.png)

This is how it should be like:
![equ3](https://user-images.githubusercontent.com/71877689/104847355-5fc3be80-5894-11eb-8b16-a544704a27b0.png)

**Comment by jbyuki** [comment]
I will continue adding support for LaTeX syntax such as matrices.

Is the rendering now looking good for most of the chemical formulas?

**Comment by jetrosut** [comment]
> I will continue adding support for LaTeX syntax such as matrices.
> 
> Is the rendering now looking good for most of the chemical formulas?
>
It indeed looks pretty neat now, including letters with both superscripts and subscripts. 

One thing I noticed though, probably after the latest commit, is that I can add superscripts or subscripts to letters but they disappear when added to numbers.

**Comment by jbyuki** [comment]
> It indeed looks pretty neat now, including letters with both superscripts and subscripts.

Great, now with LaTeX syntax, it should be much easier to type exotic formulas.

> One thing I noticed though, probably after the latest commit, is that I can add superscripts or subscripts to letters but they disappear when added to numbers.

Right, I need to add superscript/subscript to number expressions. I will fix it in the next commit.
