### ISSUE TITLE
[Bug] invalid buffer: nabla.lua:238 

### ISSUE THREAD

**Issue by chriztheanvill** [jbyuki/nabla.nvim#14]
Open neovim with and without files shows this message.
![image](https://user-images.githubusercontent.com/37992958/140607652-de2aa75c-f7b2-4e1e-a44f-9ce0320cde82.png)

**Comment by jbyuki** [comment]
Hi,

Sorry for the delayed response. Thanks for opening an issue.
Did you by any chance put the lua line `require("nabla").popup({border = "rounded"})` in your init.vim?
It's not meant to be executed directly but through a keybinding.

**Comment by chriztheanvill** [comment]
Hi, Yes, I did it.

**Comment by jbyuki** [comment]
Ok, you can remove it.
I updated the readme hopefully it should make it more clear.
If it works, you can close the issue.

**Comment by jbyuki** [comment]
Did it the error go away by removing the line in question in your init.vim?
