### ISSUE TITLE
Request for `\vee` `\wedge` `\cup` `\cap`, and questions about `\\` or `\newline` in '$$' blocks

### ISSUE THREAD

**Issue by AndOrangutan** [jbyuki/nabla.nvim#15]
**How should the input text representation look like**
> Example: `$A \vee B$`, `$A \wedge B$`, `$A \cup B$`, `$A cap B$`.

**How should the ASCII art output look like**
> Example: `A⋁B`, `A⋀B`, `A⋃B`, `A⋂B.`

I have been taking discrete mathematics, and these symbols would be quite helpful.

Also, I was wondering if there was any sort of plans for new lines in equations.

**Comment by jbyuki** [comment]
You could take a look at this [wiki article](https://github.com/jbyuki/nabla.nvim/wiki/Add-notation). It explains how to add new notation. It should be straightforward. If you make a pull requesr, I'll be happy to merge it.

**Comment by AndOrangutan** [comment]
I actually saw that after the fact, that is why I closed it. I would love to do that.
