### ISSUE TITLE
Request for in-latex text block support

### ISSUE THREAD

**Issue by cadenhenrich** [jbyuki/nabla.nvim#16]
**How should the input text representation look like**
\text{\\# Of People Reading This}=1

**How should the ASCII art output look like**
\# Of People Reading This=1

**Describe in what context you would use this notation**
Useful when previewing LaTeX in nvim before compiling to the final product.

**Additional context**
Right now the only thing displayed is `text` in place of the actual text block. Not sure if this is an option I have to turn off (was unable to find a list of config options) or just nabla doing its best to render an unknown `\` command.

**Comment by jbyuki** [comment]
You could also try the new popup option which only leaves the document as is and you can invoke popup on cursor hover to display the ASCII math.

**Comment by cadenhenrich** [comment]
This is true, although the text still shows as `text` and not the actual text.

**Comment by jbyuki** [comment]
I'm not familiar with latex how does `text{}` work. Does the backslash `\#` escape the character for a reason?

**Comment by cadenhenrich** [comment]
The `#` character, to my knowledge, designates parameters for custom macros. [This](https://tex.stackexchange.com/questions/39930/hash-character-in-latex) post tells how to just write `#` in LaTeX.
