### ISSUE TITLE
Request for \choose syntax support

### ISSUE THREAD

**Issue by cadenhenrich** [jbyuki/nabla.nvim#17]
**How should the input text representation look like**
> {5 \choose 3}

**How should the ASCII art output look like**
> ⎛ 5 ⎞
> ⎝ 3 ⎠

**Describe in what context you would use this notation**
> Discrete Math, Probability, Counting, Statistics

**Additional context**
Given the design of the "choose" notation adding a third, middle row is also an option.
```
⎛ 5 ⎞
⎜   ⎟
⎝ 3 ⎠
```

**Comment by jbyuki** [comment]
I wonder why the syntax of `\frac{x}{y}` is like this and choose is `{x \choose y}`. I would have to explore a bit in the parser to support this.
