### ISSUE TITLE
[Question] Can it be used to create a conceal layer instead?

### ISSUE THREAD

**Issue by nbCloud91** [jbyuki/nabla.nvim#2]
Thank you for creating this plugin. Would it be possible to modify this for a concealment layer which *just displays* the underlying LaTeX as ASCII math but doesn't modify the source? I don't know how something like [tex-conceal](https://github.com/KeitaNakamura/tex-conceal.vim) works, so what I'm asking for might be impossible after all.

**Comment by jbyuki** [comment]
Interesting idea, I've been playing around with virtual text which allow text overlay . I've come up with a rendering like this:

[![Untitled-Project6aee18c438bdf97d.gif](https://s4.gifyu.com/images/Untitled-Project6aee18c438bdf97d.gif)](https://gifyu.com/image/alEt)

Is it close to what you had in mind?

You can try it on your side to get a better idea. I've added the instructions in the README.md. It won't work unless you have the Neovim nightly version.

**Comment by jbyuki** [comment]
vim conceals are also neat but AFAIK it only supports single character replacement.

**Comment by nbCloud91** [comment]
This really looks good, yes this is exactly what I had in mind. I will try it out.

**Comment by nbCloud91** [comment]
I tried it out, works well enough for the typical use cases, throws errors when one inserts things which are not yet understood by the simple parser, which is well within expectations. Would it be possible to handle the exceptions gracefully?
Example:
```
\int_{\alpha}^{\beta} f(x) \,dx
```
The above throws an error `E5108: Error executing lua .../lua/nabla/latex.lua:185: bad argument #1 to 'len' (string expected, got nil)`. This is caused by the spacing command `\,`.

Also, could we persist the virtual text overlays? That way, we could get the same results as conceal based solutions.

**Comment by nbCloud91** [comment]
I am closing this issue now. Since the original feature I requested is now reasonably implemented. Thanks again for this. I may open separate issues or PRs to get `\,` (and other such spacing commands) working later.
