### ISSUE TITLE
[Feature Request] Multiline expression support

### ISSUE THREAD

**Issue by B4rc1** [jbyuki/nabla.nvim#22]
When executing `require("nabla").popup()` on an markdown latex block:
```md
$$
2 + 2 = 4
$$
```
I get:
```
E5108: Error executing lua: ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:643: bad argument #1 to 'len' (string expected,
stack traceback:
        [builtin:len]: in function 'len'
        ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:643: in function 'popup'
        [string "..."]: in function <[string "..."]:0>
Press ENTER or type command to continue
```

When executing `require("nabla").popup()` once nothing happens, after that I get:
```
E5108: Error executing lua: ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:505: Expected lua number
stack traceback:
        [C]: in function 'nvim_buf_get_extmarks'
        ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:505: in function 'edit_formula'
        ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:495: in function 'action'
        [string "..."]: in function <[string "..."]:0>
```

## System Information
- neovim git revision: https://github.com/neovim/neovim/commit/5cb45dffba730d0009d4c4d6b26efaa994727e2d
- output of `:version`
```
:version
NVIM v0.7.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/cs0wi57nzwn6729rbfkqq2p4f4hc5qf5-neovim-unwrapped-master/share/nvim"

Run :checkhealth for more info
```

**Comment by B4rc1** [comment]
on inline latex it works:
- `require("nabla").popup()`
![image](https://user-images.githubusercontent.com/10383737/154819094-774f12d9-c403-426e-8609-950b404cdacf.png)
- `require("nabla").action()`
![image](https://user-images.githubusercontent.com/10383737/154819102-926688d1-cbe5-46de-9b63-99ffc72d3297.png)

**Comment by jbyuki** [comment]
That's right, multiline equations are not supported at the moment.

**Comment by B4rc1** [comment]
Any chance of getting them supported? I heavily depend on them for my notes.

**Comment by jbyuki** [comment]
The primary issue is that with multiline `$$ ... $$` support, the parsing becomes very ambigous. Maybe I could deprecate the `action()` function in favor of only supporting `popup()`. Then it would seem feasible. I will see what I can do tomorrow morning.

**Comment by jbyuki** [comment]
Could you test if multiline is working? I removed the `action()` feature for now because it was not robust enough. Only `popup()` is supported now.

**Comment by B4rc1** [comment]
Multiline support works although single line preview is now somewhat broken:
```md
$1 + 1$
```
gives:
![image](https://user-images.githubusercontent.com/10383737/154844288-93c4248e-21ca-4cb0-a3ce-b53cb3d8bf3c.png)
although the following works as expected:
```md
$$1 + 1$$
```

Another thing is multiple single line expressions:
```md
$1 + 1 = 2$
$2 + 1 = 3$
```
![image](https://user-images.githubusercontent.com/10383737/154844345-3149bc68-de7e-4d34-a0c9-f97cbbde46d0.png)

and
```md
$1 + 1 = 2$ text $2 + 2 = 4$

$1 + 1 = 2$
$2 + 1 = 3$
```
![image](https://user-images.githubusercontent.com/10383737/154844565-6ad4ac77-b2ad-487d-bd04-00f0dd83a1b5.png)

although the following woks as expected:
```md
$$1 + 1 = 2$$ text $$2 + 2 = 4$$
```

And I can't tell if this is a byproduct of the changes you made, but `\\` for a line breaks in for example matricies stops the preview from showing up entierly

**Comment by jbyuki** [comment]
I couldn't properly reproduce those errors, but I found some coding errors in feature addition. Could you see if it's working now?

The cursor has to be inside the expression to show the popup. For example, if the cursor is placed on the first column in the following expression:
```
$$1+1$$
```
It will pick up the first `$` and second `$`, to be an inline expression and show an error because the expression is empty. I didn't want to do a whole file parsing each time to disambiguate inline vs wrapped.

Matrix should work also. I did a [test case](https://github.com/jbyuki/nabla.nvim/blob/master/test/cases/matrix.txt) which does pass on the CI. The `$$ .. $$` is implicit in the test cases.

**Comment by B4rc1** [comment]
matrix test case:
does not work:
```md
$$
\begin{pmatrix}
  1 + 1 \\
  2 + 2
\end{pmatrix}
$$
```

does work:
```md
$$
\begin{pmatrix}
  1 + 1 //
  2 + 2
\end{pmatrix}
$$

```

**Comment by jbyuki** [comment]
How is it looking now?

**Comment by B4rc1** [comment]
Found one more edge case:
this is working as expected:
![image](https://user-images.githubusercontent.com/10383737/154848548-4fdd8eef-2a12-450a-9484-2bc06feb9661.png)
this does not:
![image](https://user-images.githubusercontent.com/10383737/154848560-9476cf3b-ca82-482c-a0b4-a7a4c0444f88.png)

**Comment by B4rc1** [comment]
also having `\,` (spacing) anywhere in the latex block (regardless if single or multiline) prevents the preview from showing up at all
```
$1 \, + 1 = 2$
```
just checked, all of these prevent the popup from showing up:
```
f(x) &= x^2\! +3x\! +2
f(x) &= x^2+3x+2 
f(x) &= x^2\, +3x\, +2
f(x) &= x^2\: +3x\: +2
f(x) &= x^2\; +3x\; +2
f(x) &= x^2\ +3x\ +2
f(x) &= x^2\quad +3x\quad +2
f(x) &= x^2\qquad +3x\qquad +2
```
(see https://de.overleaf.com/learn/latex/Spacing_in_math_mode)

**Comment by B4rc1** [comment]
also
```md
$$
\begin{align}
  1 + 1 \\
  & 2 + 2
\end{align}
$$
```
prevents the popup from showing up although I'm not sure it is related to the recent changes

**Comment by jbyuki** [comment]
>Found one more edge case:
>this is working as expected:

This is really going the to the limits of the built-in grammar. If the cursor is on `$`, it will search for the next inline `$` delimiter. In other words:
```
$1+1$2+2$
```
If the cursor is on the middle `$`, it will pick `2+2`. Therefore, in the test case you showed, there is no next `$` so it fails (or falls back to search `$$` delimiter) which results in the popup you get. I'm not really sure, I can do better?

**Comment by jbyuki** [comment]
> also having \, (spacing) anywhere in the latex block (regardless if single or multiline) prevents the preview from showing up at all
This is not supported at the moment but I can it now.

**Comment by B4rc1** [comment]
> I'm not really sure, I can do better?

Yeah no big deal, thank you for your work so far

**Comment by B4rc1** [comment]
> align block is also not supported. Lots are not like equation as well.

Shouldn't there still be a popup, even if parts of the latex are not supported?

I would expect them to just be included as literal text so
```
$$
\begin{align}
  1 + 1 \\
  & 2 + 2
\end{align}
$$
```
would give
```
\begin{align}
1 + 1
2 + 2
\end{align}
```
I think this more clearly communicates that something is not implemented instead of wondering if something else did go wrong

**Comment by jbyuki** [comment]
Right, the functions in nabla weren't exposing the internal errors. I tried to expose some where it's possible with the latest commit. If you need block expressions such as align, you can open a feature request so it reminds me to implement them though I maybe won't implement them right away.

**Comment by jbyuki** [comment]
Thank you for all the testing so far, it really helped me. 💯
