### ISSUE TITLE
Request for more vertical spacing support

### ISSUE THREAD

**Issue by B4rc1** [jbyuki/nabla.nvim#23]
**How should the input text representation look like**
```
f(x) = x^2\: +3x\: +2
f(x) = x^2\; +3x\; +2
f(x) = x^2\ +3x\ +2
f(x) = x^2\quad +3x\quad +2
f(x) = x^2\qquad +3x\qquad +2
```

**How should the ASCII art output look like**
```
f(x) = x^2    +3x   +2
f(x) = x^2     +3x     +2
f(x) = x^2      +3x      +2
f(x) = x^2       +3x       +2
f(x) = x^2        +3x        +2
```
(see https://de.overleaf.com/learn/latex/Spacing_in_math_mode)

**Describe in what context you would use this notation**
I use these pretty often because they make stuff look nicer when rendered, having the popup not show up just because they are in an equation blows.

**Comment by jbyuki** [comment]
Sorry for the delay, I just added support for that now.
