### ISSUE TITLE
popup immediately disappears

### ISSUE THREAD

**Issue by wiljam144** [jbyuki/nabla.nvim#24]
Title says pretty much everything. When i press the binding the popup window flashes for a fraction of a second and then disappears never to be seen again.

**Comment by jbyuki** [comment]
The popup window is closed when a `CursorMoved` is detected. How did you keybind `popup()`?

**Comment by wiljam144** [comment]
i bind it to `<A-m>` but it closes even if i bind it to `<leader>p`

**Comment by wiljam144** [comment]
I've managed to fix the issue for some reason comment didn't work as comment and caused the popup to close.
