### ISSUE TITLE
Support equation enviroment

### ISSUE THREAD

**Issue by ihasdapie** [jbyuki/nabla.nvim#25]
For most of my notes I use the `equation` environment for numbered equations, etc. Would it be possible for `nabla.nvim` to support previewing math in an `equation`? I understand that parsing this could be messy so I'm thinking a good alternative would be to provide a method to preview a visual-selected region of text -- and then the user can map/bind that as they see fit, perhaps with `vimtex` textobjects or treesitter, etc.

Thanks for the great plugin! If there is a way I can help with this let me know.

**Comment by jbyuki** [comment]
I believe the visual selection would be the best and fairly easy to implement. If you have time, I would actually welcome the PR to do this. You can take inspiration from [this](https://github.com/jbyuki/nabla.nvim/blob/master/src/viewmode/popup.lua.t) which was done by another contributor and the associated [PR](https://github.com/jbyuki/nabla.nvim/pull/13) where I explain how to add code in nabla.nvim.

Feel free to ask any questions here.

**Comment by jbyuki** [comment]
Fixed by #44
