### ISSUE TITLE
New ASCII is generated instead of replacing existing equation on modify

### ISSUE THREAD

**Issue by clstb** [jbyuki/nabla.nvim#3]
See Title. Anyway very nice plugin, though I think this should be default behaviour.
Also what do you think about making the ASCII equation hide when moving the cursor on it? I.e smooth switching between view and edit mode.

**Comment by jbyuki** [comment]
Thanks. That actually makes a lot of sense. I could try implementing something like a view mode.

**Comment by jbyuki** [comment]
Just a rough sketch but I added a viewmode, could you give it a try? It can be seen in action using `require"nabla".toggle_viewmode()`.

**Comment by clstb** [comment]
Functionality wise that works fine 👍 
What would be left to do is enabling/disabling it for each equation based on cursor position.

**Comment by jbyuki** [comment]
Can you give it another try? I added some functionnalities.
* Switch to view mode : require"nabla".toggle_viewmode()
* Edit formula : hover cursor and require"nabla".edit_formula(). Press Enter to confirm.
* Replace current latex : hover cursor and require"nabla".replace_this().

**Comment by jbyuki** [comment]
Alternatively I added a context sensitive function which does everything `require"nabla".action()` to stay in the spirit of nabla.

**Comment by clstb** [comment]
👍 
I would automate the action function depending on cursor position and let the formula editing take place in the actual buffer like it was before. Don't know what your vision is for this though.

**Comment by jbyuki** [comment]
Agreed. I wanted to avoid any shifting introduced by switching between edit mode/view mode (the current line shifts when switching file). But if the edit is done in place in the file, it would be fine. Let's see what it's like.

**Comment by jbyuki** [comment]
I pushed the suggested changes. How does it feel now?

**Comment by clstb** [comment]
Seems good, filename is modified though (.nabla is appended).

**Comment by jbyuki** [comment]
This is to avoid saving hacks. But it does also write to the original file. I will stick to this design if you don't have see any major drawback with this approach.

**Comment by jbyuki** [comment]
I was playing with some other project and found some code which avoids temporary files. Now I guess it's better.
