### ISSUE TITLE
Math mode with `\( \)` and `\[ \]`

### ISSUE THREAD

**Issue by tarsobcaldas** [jbyuki/nabla.nvim#30]
LaTeX math mode is entered using `\( \)` and `\[ \]`, but I could only get the plugin to work inside `$ $` and `$$ $$`. Also, is it possible to add the math display environments?

**Comment by jbyuki** [comment]
I would suggest a solution proposed in #25 would also fit for this use case.

**Comment by jbyuki** [comment]
Should be fixed by #44
