### ISSUE TITLE
use treesitter

### ISSUE THREAD

**Issue by max397574** [jbyuki/nabla.nvim#39]
You could use treesitter which imo would be way cleaner to detect math areas.
this could be done with a function like this
<https://github.com/max397574/nabla.nvim/blob/390d1a2a12df22e3f797c629aa82fe98ac9aa5d2/lua/nabla/utils.lua#L2-L67>
you could also use `get_node_range` and `nvim_buf_get_text` or directly `get_node_text` to get the actual math

**Comment by max397574** [comment]
<https://github.com/max397574/nabla.nvim/blob/3704e556f8880c843da5257714c2baa327ce1943/lua/nabla/init.lua#L935-L957>
here is an example of how I implemented this and it works really goo with all the different math environments

**Comment by jbyuki** [comment]
Thank you for your suggestion. This is indeed a good idea, I've used treesitter in other of my plugins for similar purposes and it works well. 

I will look into this.

**Comment by jbyuki** [comment]
Can the code sample you provided be directly pasted in the code? Or do I need other things as well?

I am asking this because without the proper treesitter parser, it won't give any results back I assume. Maybe do you know of a parser which would properly parse the file to detect math areas?

**Comment by max397574** [comment]
I just use the parser from the `nvim-treesitter` repo
I'd have to check again if the sample could be pasted directly

**Comment by max397574** [comment]
```diff
diff --git a/lua/nabla.lua b/lua/nabla.lua
index ee67f98..630c280 100644
--- a/lua/nabla.lua
+++ b/lua/nabla.lua
@@ -1,6 +1,9 @@
 -- Generated using ntangle.nvim
 -- local parser = require("nabla.parser")
 local parser = require("nabla.latex")
+local ts_utils = require("nvim-treesitter.ts_utils")
+local utils=require"nabla.utils"
+
 
 local ascii = require("nabla.ascii")
 
@@ -333,26 +336,50 @@ local function gen_drawing(lines)
 end
 
 local function popup(overrides)
-  local buf = vim.api.nvim_get_current_buf()
-  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
-  local line
+    if not utils.in_mathzone() then
+        return
+    end
+    local line
 
-  if not row then
-    row, col = unpack(vim.api.nvim_win_get_cursor(0))
-  end
+    cur_line = line
+
+    local math_node = utils.in_mathzone()
 
-  local srow, scol, erow, ecol, del = find_latex_at(buf, row, col)
+    local srow, scol, erow, ecol = ts_utils.get_node_range(math_node)
+    local lines = vim.api.nvim_buf_get_text(0, srow, scol, erow, ecol, {})
 
-  if srow then
-    local lines = vim.api.nvim_buf_get_lines(buf, srow-1, erow, true)
-    lines[#lines] = lines[#lines]:sub(1, ecol)
-    lines[1] = lines[1]:sub(scol+1)
     line = table.concat(lines, " ")
+    line = line:gsub("%$", "")
+    line = line:gsub("\\%[", "")
+    line = line:gsub("\\%]", "")
+    line = line:gsub("^\\%(", "")
+    line = line:gsub("\\%)$", "")
+    local whitespace = string.match(line, "^(%s*)%S")
+    line = vim.trim(line)
+    if line == "" then
+        return
+    end
 
-  else
-    vim.api.nvim_echo({{"Please put the cursor inside an inline latex expression and try calling this function again.", "ErrorMsg"}}, false, {})
-    return
-  end
+  -- local buf = vim.api.nvim_get_current_buf()
+  -- local row, col = unpack(vim.api.nvim_win_get_cursor(0))
+  -- local line
+  --
+  -- if not row then
+  --   row, col = unpack(vim.api.nvim_win_get_cursor(0))
+  -- end
+  --
+  -- local srow, scol, erow, ecol, del = find_latex_at(buf, row, col)
+  --
+  -- if srow then
+  --   local lines = vim.api.nvim_buf_get_lines(buf, srow-1, erow, true)
+  --   lines[#lines] = lines[#lines]:sub(1, ecol)
+  --   lines[1] = lines[1]:sub(scol+1)
+  --   line = table.concat(lines, " ")
+  --
+  -- else
+  --   vim.api.nvim_echo({{"Please put the cursor inside an inline latex expression and try calling this function again.", "ErrorMsg"}}, false, {})
+  --   return
+  -- end
 
 
   local success, exp = pcall(parser.parse_all, line)
```
and adding what I sent above in utils.lua did the job for me

**Comment by max397574** [comment]
the only problem I encountered was that sometimes I'd get 
![Screenshot 2022-10-08 at 17 11 42](https://user-images.githubusercontent.com/81827001/194714372-234aba03-6ab5-4f25-8728-15ca95c9838b.png)
and there really is a call to a function which doesn't exist
perhaps sth went wrong with ntangle there

**Comment by max397574** [comment]
I was able to figure that out
the function exists but it's defined below the call
this could be fixed like this:
```diff
diff --git a/lua/nabla/ascii.lua b/lua/nabla/ascii.lua
index f78ffd1..8dd34e2 100644
--- a/lua/nabla/ascii.lua
+++ b/lua/nabla/ascii.lua
@@ -7,6 +7,8 @@ local put_if_only_sub
 
 local put_if_only_sup
 
+local to_ascii
+
 
 local style = {
 	plus_sign = " + ",
@@ -1352,7 +1354,7 @@ function put_if_only_sup(exp, g)
   return g
 end
 
-local function to_ascii(exp)
+to_ascii=function(exp)
 	local g = grid:new()
 	if not exp then
 		print(debug.traceback())
```

**Comment by max397574** [comment]
the last two things here are unrelated to treesitter
I think they just happened because other math things like $$..$$ or \[...\] were also parsed
I can open a separate issue if you'd like to

**Comment by jbyuki** [comment]
>the last two things here are unrelated to treesitter
>I think they just happened because other math things like
>or [...] were also parsed

Is it not? I thought using a treesitter approach would eliminate all these delimiters problems with proper parsing.

**Comment by jbyuki** [comment]
> I just use the parser from the nvim-treesitter repo

Oh I didn't read the code you provided carefully but now I see it's using a latex parser. Didn't know there was one! That's wonderful, we can use that, probably the utils code can be added here without any modifications. I still need to find a way so that people not using ntangle can contribute because this is non-optimal...

**Comment by max397574** [comment]
> > the last two things here are unrelated to treesitter
> > I think they just happened because other math things like
> > or [...] were also parsed
> 
> Is it not? I thought using a treesitter approach would eliminate all these delimiters problems with proper parsing.

this has nothing todo with these delimiters
I just think that somehow other parts of the ascii code are reached which cause this error
because I don't recall ever seeing it before
and it obivously is a mistake in the code that isn't related to using treesitter or not

**Comment by max397574** [comment]
> > I just use the parser from the nvim-treesitter repo
> 
> Oh I didn't read the code you provided carefully but now I see it's using a latex parser. Didn't know there was one! That's wonderful, we can use that, probably the utils code can be added here without any modifications. I still need to find a way so that people not using ntangle can contribute because this is non-optimal...

yes ntangle is also the reason why I just didn't add those things in a draft pr xD

**Comment by jbyuki** [comment]
> yes ntangle is also the reason why I just didn't add those things in a draft pr xD
understandable, although if I didn't have ntangle, I would have never written such a big plugin in the first place. So it's a sad tragedy, hopefully I/somebody comes up with something better to manage this.

**Comment by jbyuki** [comment]
> this has nothing todo with these delimiters
> I just think that somehow other parts of the ascii code are reached which cause this error
> because I don't recall ever seeing it before
> and it obivously is a mistake in the code that isn't related to using treesitter or not

Yes, maybe open a new issue for that. We can leave this issue here for the treesitter implementation in nabla.nvim.

**Comment by max397574** [comment]
just tested
with small adjustments to what I sent above we could also support 
```latex
\begin{equation}
    ...
\end{equation}
```

**Comment by max397574** [comment]
> understandable, although if I didn't have ntangle, I would have never written such a big plugin in the first place. So it's a sad tragedy, hopefully I/somebody comes up with something better to manage this.

would it be an option for you to develop in lua?

**Comment by max397574** [comment]
it would be quite a big step to get there since the lua code is really really messy atm
but perhaps it would be worth it because more people would/could contribute

**Comment by jbyuki** [comment]
Actually I think that using the ntangle tools, it would be quite manageable to refactor the code. Give it 1-2 days, and it would be done.

But I'm just interested by ntangle and this type of programming. It is beyond me. Like some people like to use fennel or teal. Basically, if the code would be converted to Lua, I would not have any interest in contributing to it anymore. That's my point.

I feel like ntangle allows me to program at 3x speed, so basically what you're saying is go back to 1x speed. I might just be stupid but that's how I feel about the whole thing.

**Comment by jbyuki** [comment]
But I think people contributing with normal Lua code to this repository is still not out of the question. I have some ideas I need to test.

**Comment by max397574** [comment]
so about the treesitter thing
should I look into how ntangle works to try to contribute it myself or will u do (I could look at the pr to see if it is what I imagined)?

**Comment by jbyuki** [comment]
I will do it if you are not particularly akin to try ntangle. I will leave a PR for you to check yes.
Just give me some time, I'm currently refactoring the whole thing, and fixing some serious issues I found through the other issues you opened. Thank you for that btw.

**Comment by max397574** [comment]
you're welcome
thank you for your fast responses and the great discussions

since I have quite a lot of time the next week I could look into ntangle
it's something I've never done before so it could be interesting to get into
can I hit you up if I'm stuck with the pr?

**Comment by jbyuki** [comment]
Likewise, 
of course feel free to hit me up anytime.

**Comment by max397574** [comment]
I give up
I rly don't like this style of programming and it's not worth for me spending so much time to learn the syntax if you can do it so much faster

**Comment by jbyuki** [comment]
Fair enough, I will see if I can push some commits on top of your PR to fix that

**Comment by max397574** [comment]
should we perhaps make a post about this or mention it in this-week-in-neovim?
(I think the second one would be quite a good option)
since a lot of people wanted more types of math to be supported which is now the case

**Comment by max397574** [comment]
I'll add it to this section
<https://this-week-in-neovim.org/2022/Oct/03#updates>

**Comment by max397574** [comment]
ok for you @jbyuki ?
