### ISSUE TITLE
Running nabla two times results in cryptic error

### ISSUE THREAD

**Issue by clstb** [jbyuki/nabla.nvim#4]
1. Write latex equation
2. Run `:lua require("nabla").place_inline()`
3. Run it again

`E5108: Error executing lua ...clstb/.local/share/nvim/plugged/nabla.nvim/lua/nabla.lua:257: bad argument #1 to 'len' (string expected, got nil)`

Tried with this latex `\frac{ 1 - \sum_{l \leq k+n} (1-p)^{l-1}p }{ 1 - \sum_{l \leq k} (1-p)^{l-1}p }`

**Comment by jbyuki** [comment]
This is probably expected because you're running nabla on the ASCII art. I won't fix it now before implementing view mode.

**Comment by jbyuki** [comment]
This should be fixed.
