### ISSUE TITLE
attempt to concatenate field 'sym' (a nil value)

### ISSUE THREAD

**Issue by max397574** [jbyuki/nabla.nvim#46]
`...nvim/site/pack/packer/opt/nabla.nvim/lua/nabla/ascii.lua:1723: attempt to concatenate field 'sym' (a nil value)`
some equations where this error occurs:
`\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}`
`\begin{matrix} x^2 & a_H \\ \frac{1}{2} & d^2 \end{matrix}`
(from test file)
it seems to occur with every thing that uses `pmatrix` I'm quite (not 100% though) sure that it didn't occur with my pr before you made it be generated by ntangle

**Comment by jbyuki** [comment]
Yes, this must be caused by the large refactor I did previously so not your PR. I will have a look.
