### ISSUE TITLE
weird behavior of `virt_lines`

### ISSUE THREAD

**Issue by max397574** [jbyuki/nabla.nvim#49]
I have the example test file from the repo here
when I comment out everything except for the first three equations and `:lua require"nabla".toggle_virt()`
I get errors from https://github.com/jbyuki/nabla.nvim/issues/46, https://github.com/jbyuki/nabla.nvim/issues/47 and https://github.com/jbyuki/nabla.nvim/issues/48
when I delete the other equations I don't get problems
is it possible that the virt_lines don't recognize comments?

**Comment by jbyuki** [comment]
Could this be solved by using treesitter for virt_lines as well? You might be able to judge that.

**Comment by max397574** [comment]
yes perhaps it could
treesitter definitely won't do anything with the comments

**Comment by max397574** [comment]
should I try to figure out where the change needs to be made? (I'd prefer if not since I'm not rly familiar with this code)

**Comment by jbyuki** [comment]
I'm looking into it. It should not be too difficult using your provided code.
