### ISSUE TITLE
No popup

### ISSUE THREAD

**Issue by drzhivago420** [jbyuki/nabla.nvim#51]
Tried disabling all plugings except TS and nabla.
I've tried multiple maps, aswel as just writing ":lua require("nabla").popup()" in command mode.
Latex parser is installed.
Canot get any feedback at all.
NVIM 0.7.2

**Comment by drzhivago420** [comment]
😅 thanks, guess it was obvious

**Comment by jbyuki** [comment]
Well, not really. Previously, it had a warning message, but we forgot to put it again with the new treesitter implementation. So thanks for pointing this out! It will probably save a few people's time.

**Comment by drzhivago420** [comment]
Any way to copy the content to the clipboard without using the mouse?

**Comment by jbyuki** [comment]
Currently no. Why would you need this?
It's always possible to use the underlying lua API to extract the ASCII content from a Latex formula.

**Comment by drzhivago420** [comment]
Well, I was checking the plugin to have plaintext shareable equations. So, most of the time I open the popup is to paste it into the file.

**Comment by jbyuki** [comment]
You could try with `:lua require"nabla".popup({focusable=true})` then use some command to jump into the window (I don't remenber currently). I personally always use the mouse (`:set mouse=a`) and click into the floating window to focus it. That's the best solution I came up with now.

**Comment by max397574** [comment]
@jbyuki I wouldn't add a warning
imo it's obvious already
perhaps add a notice to the readme if you think it isn't
but this could be annoying if e.g. someone just uses a CursorHold autocommand

**Comment by jbyuki** [comment]
Fair point, I'll add this into the README instead. Thanks @max397574 .
