### ISSUE TITLE
Add support for \mathcal{...}

### ISSUE THREAD

**Issue by mhtoribio** [jbyuki/nabla.nvim#53]
**How should the input text representation look like**
> Example: \mathcal{F} \mathcal{L}

**How should the ASCII art output look like**
> Example: 𝓕 𝓛

**Describe in what context you would use this notation**
Symbols I often need to write for notes on eg. lectures.
> Example: Fourier or Laplace transform symbol as \mathcal{F} and \mathcal{L}

**Additional context**
An alternative is to add the \mathscr notation from the mathrsfs package.

**Comment by jbyuki** [comment]
For a start, I could implement something similar to `\mathbb` which is supported. I think this would cover this use case.

**Comment by jbyuki** [comment]
The symbol table for `\mathcal` is here:

https://github.com/jbyuki/nabla.nvim/blob/43b2940f8906653f4cad5c8548f8dae117e6a071/lua/nabla/ascii.lua#L1022-L1049

Feel free to PR if you think it requires more symbols.

**Comment by mhtoribio** [comment]
This covers my use case perfectly. Thank you for your quick incorporation of this feature in this awesome project! I'll submit a PR if I run into more symbols, which I feel are required.
