### ISSUE TITLE
Add support for ∥

### ISSUE THREAD

**Issue by codingTornado** [jbyuki/nabla.nvim#60]
**How should the input text representation look like**
> \\|x\\|

**How should the ASCII art output look like**
> ∥x∥

**Describe in what context you would use this notation**
> It's used to indicate the [norm for a vector](https://en.wikipedia.org/wiki/Norm_(mathematics))

**Additional context**

**Comment by jbyuki** [comment]
Thank you for your report, please do more if you need.
