### ISSUE TITLE
Add mathbb number support

### ISSUE THREAD

**Issue by codingTornado** [jbyuki/nabla.nvim#61]
**How should the input text representation look like**
> \mathbb{0}

**How should the ASCII art output look like**
> 𝟘 

**Describe in what context you would use this notation**
> It's sometimes used to note the set only containing the addition neutral element. I've also encountered the 𝟚 as the binary set. Doing all 10 numbers might be a good idea, from U+1D7D8 to U+1D7E1 (𝟘, 𝟙, 𝟚, 𝟛, 𝟜, 𝟝, 𝟞, 𝟟, 𝟠, 𝟡)

Thank you for the hard work!

**Comment by jbyuki** [comment]
This should be implemented BUT I get rendering issues with my terminal emulator (Windows Terminal). I can confirm it's working in nvim-qt so it might just be an upstream issue. Thanks again!
