### ISSUE TITLE
Configuration example for lazy.nvim plugin manager in readme

### ISSUE THREAD

**Issue by Vaisakhkm2625** [jbyuki/nabla.nvim#62]
I am recently started using nabla, and i am loving it....

This is request to add  installation instructions for lazy.nvim plugin manager Readme file.

``` lua
  {
    "jbyuki/nabla.nvim",
    keys = {
      { "<leader>nl", function() require("nabla").popup() end, desc = "Notation", },
    },
    config = function()
      require("nabla").enable_virt()
    end,
  },

```
got it from a medium article (https://alpha2phi.medium.com/modern-neovim-pde-part-2-679a5fc0a407)

i tried to mess around a lot of time to get this working...
first i tried this, which was throwing errors

``` lua
  {
    "jbyuki/nabla.nvim",
    opts = {
      autogen = true, -- auto-regenerate ASCII art when exiting insert mode
      silent = true, -- silents error messages
    },
  },
```

**Comment by jbyuki** [comment]
A few points maybe that could help:
* `enable_virt()` should also be a keymap. It is enabled on demand by the user
* `config` can be empty. nabla.nvim does not require any.
* The options `autogen` and `silent` should be passed directly to `enable_virt()`

Hope this helps. If it's functional, we can also merge that for other people to see as lazy.nvim is far more used than packer.nvim.

**Comment by jbyuki** [comment]
I guess 

```lua
{
   "jybuki/nabla.nvim"
}
```

is already a good starting point. It's the equivalent to the other install instructions and users can always configure their setup in separate .lua config files.

**Comment by Vaisakhkm2625** [comment]
so can i close this issue? 

(or is it okk to  add above points to wiki?)

**Comment by jbyuki** [comment]
Discussion is still open but we can close this for now.

**Comment by thiswillbeyourgithub** [comment]
> I guess
> 
> ```lua
> {
>    "jybuki/nabla.nvim"
> }
> ```
> 
> is already a good starting point. It's the equivalent to the other install instructions and users can always configure their setup in separate .lua config files.

You made a typo in your username. I was pulling my hair for nothing :)

**Comment by thiswillbeyourgithub** [comment]
If anyone is wondering how to add nabla to neovim using lazy here's how I did:

In my lazy.lua:
```
-- https://github.com/jbyuki/nabla.nvim/issues/35
vim.api.nvim_set_keymap("", "<leader>p", ":lua require('nabla').toggle_virt({autogen=true, silent=true})<CR>", { noremap = true, silent = true }) -- leader+p to toggle displaying the equation
require("nabla").enable_virt({autogen=true, silent=true}) --enabled by default
```

In my plugins.lua:
```
    {
    "jbyuki/nabla.nvim"
    }
```

**Comment by Vaisakhkm2625** [comment]
> If anyone is wondering how to add nabla to neovim using lazy here's how I did:
> 
> In my lazy.lua:
> 
> ```
> -- https://github.com/jbyuki/nabla.nvim/issues/35
> vim.api.nvim_set_keymap("", "<leader>p", ":lua require('nabla').toggle_virt({autogen=true, silent=true})<CR>", { noremap = true, silent = true }) -- leader+p to toggle displaying the equation
> require("nabla").enable_virt({autogen=true, silent=true}) --enabled by default
> ```
> 
> In my plugins.lua:
> 
> ```
>     {
>     "jbyuki/nabla.nvim"
>     }
> ```

it would be nice if you could enable syntax highlighting 😅 (you can use  `  ```lua <code> ```   ` for it ) 

i was also working on a similar plugin that works without ascii rendering, instead uses terminal image protocols to show image of latex equation (uses tectonic under the hood, so no need to install 1000s of dependencies of texlive just for showing some eqs), though i didn't had time for quiet a while, so need to work on it in the future.. 

other plugins might do the same (this is old list ) - https://gist.github.com/Vaisakhkm2625/909d9222e2883648635954f1323bc4e3

**Comment by thiswillbeyourgithub** [comment]
> it would be nice if you could enable syntax highlighting 😅 (you can use  ```lua <code> ```  for it )

Done! Thanks

Nice work on your plugin. I'll try to keep an eye on it!
