### ISSUE TITLE
Add dots

### ISSUE THREAD

**Issue by ahmedkhalf** [jbyuki/nabla.nvim#7]
**How should the input text representation look like**
```tex
$$ T^{i_1 i_2 \dots i_p}_{j_1 j_2 \dots j_q} = T(x^{i_1},\dots,x^{i_p},e_{j_1},\dots,e_{j_q}) $$
```

**How should the ASCII art output look like**
```

   i₁i₂...iₚ  ⎛ i₁      iₚ            ⎞
  T         =T⎜x  ,...,x  ,e  ,...,e  ⎟
   j₁j₂...j   ⎜             j₁      j ⎟
           q  ⎝                      q⎠


```

**Describe in what context you would use this notation**
Math

**Comment by jbyuki** [comment]
Thank you for posting an issue.

The following notations are now supported:
* `cdots` : `⋯`
* `ldots` : `…`
* `ddots` : `⋱`
* `vdots` : `⋮`

**Comment by ahmedkhalf** [comment]
but what about `\dots` ?

**Comment by jbyuki** [comment]
If I alias it to `\ldots` will it suffice?

**Comment by ahmedkhalf** [comment]
yea

**Comment by jbyuki** [comment]
Done, you can now use `\dots`.

**Comment by ahmedkhalf** [comment]
thanks
