### ISSUE TITLE
Using with markdown in vimwiki

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [jbyuki/nabla.nvim#8]
I am trying to use nabla.nvim in a md file. However, it keeps reporting expect a lua number line 482. Are there any solutions ?

![image](https://user-images.githubusercontent.com/71932200/129466396-a1290a21-0d9e-4eb9-a672-9cae24044e4b.png)

**Comment by jbyuki** [comment]
I cannot reproduce this error on my config.

Does it also give an error on an empty file (not markdown)?

**Comment by SleepyCatOnTheBed** [comment]
Sorry for late response, i reinstall the plugin and everything works flawlessly. Thank you for your help and great plugins.
