### ISSUE TITLE
"E492: Not an editor command: nabla" with Lazy 

### ISSUE THREAD

**Issue by ostap-tymchenko** [jbyuki/nabla.nvim#89]
![Screenshot_20241007_042823](https://github.com/user-attachments/assets/135d59f5-8a77-412f-9256-5b2ad1e6017a)
![Screenshot_20241007_042408](https://github.com/user-attachments/assets/ddd81a53-9b2b-4f10-87a1-3edfba20906a)

### My dots:
https://github.com/ostap-tymchenko/ani-dots

### My neovim config:
.
├── init.lua
├── lazy-lock.json
├── lua
│   ├── config
│   │   ├── colorscheme.lua
│   │   ├── keys.lua
│   │   ├── lazy.lua
│   │   ├── lsp.lua
│   │   ├── options.lua
│   │   ├── [ ... ]
│   └── plugins
│       ├── nabla.lua
│       ├── [ ... ]

5 directories, 37 files

### Nvim info:
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068

### System info
Operating System: Nobara Linux 39
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.6.2
Kernel Version: 6.8.12-200.fsync.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7640U w/ Radeon 760M Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Framework
Product Name: Laptop 13 (AMD Ryzen 7040Series)
System Version: A5

**Comment by max397574** [comment]
Why would you try to use this command? Afaict nabla never claims to provide a user command.

And either way user commands can never even start with lowercase letters

**Comment by ostap-tymchenko** [comment]
Sorry about that I misunderstood what the keybinding was.

**Comment by max397574** [comment]
could you please close this issue then?

**Comment by ostap-tymchenko** [comment]
I closed the issue as non planned.

**Comment by ostap-tymchenko** [comment]
I'm still seeing the issue as open so ill close it as completed instead.
